name: Basic Secrets

on:
  workflow_dispatch:

jobs:
  show-secrets:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Access different types of secrets
        run: |
            echo "Secret 1: $SECRET_1"
            echo "Secret 2: $SECRET_2"
            echo "Secret 3: $SECRET_3"
        env:
          SECRET_1: ${{ secrets.SECRET_1 }}
          SECRET_2: ${{ secrets.SECRET_2 }}
          SECRET_3: ${{ secrets.SECRET_3 }}