name: Advanced Environment Variables

on:
  workflow_dispatch:
jobs:
  show-vars:
    runs-on: ubuntu-latest
    environment: 
      name: "development"
    steps:
      - name: Print variables
        run: |
          echo "Echo url from env: $URL"
          echo "Echo name from env: $NAME"
          echo "Echo last name from vars: $LAST_NAME"
        env:
          URL: ${{ env.URL }}
          NAME: ${{ env.NAME }}
          LAST_NAME: ${{ vars.LAST_NAME }}
